version: '3.8'

services:
  mosquitto:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

  py_listener:
    build: ./py_listener
    depends_on:
      - mosquitto
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./py_listener/log:/app/log
